### ISSUE TITLE
VSCode directory in master branch.

### ISSUE THREAD

**Issue by rfootq** [cubemalevich/bogdangram#1]
Hello everyone. In my opinion, the editor settings are unnecessary. I'm about./VSCode
For example, it's useless on my system.

**Comment by ghost** [comment]
@rfootq, what system do you mean

**Comment by rfootq** [comment]
I'm sorry, for example, I use the **VIM** editor. In this case, the VS Code settings are unnecessary for me (maybe someone else). Although, if the project requires it, in no case, I do not pretend.

**Comment by cubemalevich** [comment]
I use VSCode, it’s quite convenient and intuitive (quick server startup)

**Comment by rfootq** [comment]
Great!
